# Generated by Django 2.0.6 on 2018-10-19 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('place', models.CharField(blank=True, max_length=500)),
                ('administrators', models.ManyToManyField(related_name='_event_administrators_+', to=settings.AUTH_USER_MODEL)),
                ('attendees', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.Group')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('invited', models.ManyToManyField(related_name='_event_invited_+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MeetingRules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_delay', models.DurationField()),
                ('maximum_delay', models.DurationField()),
                ('duration', models.DurationField()),
                ('administrators', models.ManyToManyField(related_name='_meetingrules_administrators_+', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TimeRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('duration', models.DurationField()),
            ],
        ),
        migrations.AddField(
            model_name='meetingrules',
            name='possible_time_ranges',
            field=models.ManyToManyField(to='agenda.TimeRange'),
        ),
    ]
