# Generated by Django 2.1.1 on 2018-10-19 22:23

from django.db import migrations, models
import django.db.models.deletion
import groups.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_auto_20181019_2223'),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreasactionForGroup',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounting.Transaction')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='groups.Group', validators=[groups.models.TreasactionForGroup.validate_TransacGroup])),
            ],
            bases=('accounting.transaction',),
        ),
    ]
